### ISSUE TITLE
签名文件不见了？

### ISSUE THREAD

**Issue by cbuemc** [yangchong211/YCStudyCpp#13]
Keystore file /Users/dengyi/Desktop/demo/YCAudioPlayer-master/ycPlayer.jks not found for signing config 'debug'.

**Comment by xiyangyang8110** [comment]
同问，源码下载下来，运行不了，报没有ycPlayer.jks

**Comment by lichaohuilala** [comment]
俺也是！

**Comment by lichaohuilala** [comment]
自己新建一个就好了
